pull_request_rules:
  - name: Assign the main reviewers
    conditions:
      - check-success=CodeFactor
    actions:
      request_reviews:
        users:
          - guilyx
  - name: Automatic merge on approval
    conditions:
      - approved-reviews-by>=1
      - check-success=lint (macos-latest, 3.6)
      - check-success=test (macos-latest, 3.6)
      - check-success=lint (macos-latest, 3.7)
      - check-success=test (macos-latest, 3.7)
      - check-success=lint (macos-latest, 3.8)
      - check-success=test (macos-latest, 3.8)
      
      - check-success=lint (ubuntu-latest, 3.6)
      - check-success=test (ubuntu-latest, 3.6)
      - check-success=lint (ubuntu-latest, 3.7)
      - check-success=test (ubuntu-latest, 3.7)
      - check-success=lint (ubuntu-latest, 3.8)
      - check-success=test (ubuntu-latest, 3.8)
      
      - check-success=CodeFactor
    actions:
      merge:
        method: merge
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: Ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it @{{author}}? 🙏