codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "setup.py"
  - "examples/*"
  - "src/discord_bot/*"
  - "src/gmail_bot/*"
  - "src/telegram_bot/*"
  - "src/twitter_bot/*"
  - "src/shops/binance.py"
  - "src/shops/kucoin.py"
  - "src/shops/nexo.py"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no